// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rcngmnxwdrvqzbwutcev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbmdtbnh3ZHJ2cXpid3V0Y2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0OTIzMDgsImV4cCI6MjA5MzA2ODMwOH0.vd67NlUp3Y5T9d_QGDoEGBmSpsAFk1rvTvw_KqWSyCo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);